server {
    listen 80;
    server_name _;

    # React static files
    root /usr/share/nginx/html;
    index index.html;

    # ---- Frontend routing (React SPA) ----
    location / {
        try_files $uri /index.html;
    }

    # ---- Backend proxy ----
    location /api/ {
        proxy_pass http://rc-be:1000; # adding trailing slash remove 'api' from the path

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_cache_bypass $http_upgrade;
    }

    # Optional, useful for debugging: Ollama passthrough
    # allows frontend or browser reach Ollama directly via nginx
    location /ollama/ {
        proxy_pass http://molly:11434/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
