services:
  molly:
    image: molly:latest
    container_name: molly
    restart: unless-stopped
    networks:
      - nai
    expose:
      - "11434"
    volumes:
      - ollama:/root/.ollama

  rc-be:
    build:
      context: ./backend
    container_name: be
    restart: unless-stopped
    ports:
      - "1000:1000"
    environment:
      - HOST=0.0.0.0
      - PORT=1000
      - OLLAMA_BASE_URL=http://molly:11434
    command:
      - sh
      - -c
      - uvicorn main:app --host ${HOST:-0.0.0.0} --port ${PORT:-1000} --workers 4
    networks:
      - nai

  wfe:  # frontend service
    build:
      context: ./frontend
    container_name: wfe
    restart: unless-stopped
    depends_on:
      - be
    ports:
      - "80:80"
    networks:
      - nai

networks:
  nai:
    # external: true

volumes:
  ollama:

